/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense_system.view;


import defense_system.DefenseObserver;
import defense_system.Observer;
import defense_system.Observer;
import defense_system.Observer;
import defense_system.Observer;
import defense_system.Observer;
import defense_system.Observer;
import defense_system.Observable;
import defense_system.StrengthEnum;
import defense_system.view.Helicopter;
import defense_system.view.Helicopter;
import defense_system.view.Helicopter;
import java.awt.TextArea;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.event.AncestorListener;
import javax.swing.event.ChangeListener;



/**
 *
 * @author ASUS
 */
public class MainController extends javax.swing.JFrame {

    /**
     * Creates new form MainController
     */
    
    private static Observer observer;
    private int areaCleared;
    
    private String mainMsg;
    private  StrengthEnum strengthEnum;
    private int strength;
   
    
    public MainController(Observer observer){
        this.observer=observer;
        initComponents();
        txtDisplayMsg.setEditable(false);
        displayDetails.setEditable(false);
        setVisible(true);
    }

    

    

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCollectInfo = new javax.swing.JButton();
        selectDefense = new javax.swing.JComboBox<>();
        soldierCount = new java.awt.Label();
        fuelCount = new java.awt.Label();
        ammoCount = new java.awt.Label();
        label1 = new java.awt.Label();
        cbxAreaClear = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayDetails = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDisplayMsg = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSendMsg = new javax.swing.JTextArea();
        strengthSlider = new javax.swing.JSlider();
        cbxPrivate = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainController");

        btnCollectInfo.setBackground(new java.awt.Color(102, 153, 255));
        btnCollectInfo.setText("Collect information");
        btnCollectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectInfoActionPerformed(evt);
            }
        });

        selectDefense.setBackground(new java.awt.Color(34, 153, 255));
        selectDefense.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarine" }));
        selectDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDefenseActionPerformed(evt);
            }
        });
        selectDefense.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectDefensePropertyChange(evt);
            }
        });

        soldierCount.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        soldierCount.setText("Soldier Count\n");

        fuelCount.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fuelCount.setText("Fuel Count\n");

        ammoCount.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ammoCount.setText("Ammo Count\n\n");

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Position\n");

        cbxAreaClear.setText("Area Clear");
        cbxAreaClear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAreaClearItemStateChanged(evt);
            }
        });
        cbxAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAreaClearActionPerformed(evt);
            }
        });

        displayDetails.setColumns(20);
        displayDetails.setRows(5);
        jScrollPane3.setViewportView(displayDetails);

        btnSend.setBackground(new java.awt.Color(0, 102, 102));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setForeground(new java.awt.Color(204, 204, 204));
        btnSend.setText("Send");
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSendMousePressed(evt);
            }
        });
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtDisplayMsg.setColumns(20);
        txtDisplayMsg.setRows(5);
        jScrollPane4.setViewportView(txtDisplayMsg);

        txtSendMsg.setColumns(20);
        txtSendMsg.setRows(5);
        jScrollPane1.setViewportView(txtSendMsg);

        strengthSlider.setMajorTickSpacing(20);
        strengthSlider.setMinorTickSpacing(10);
        strengthSlider.setPaintLabels(true);
        strengthSlider.setPaintTicks(true);
        strengthSlider.setSnapToTicks(true);
        strengthSlider.setValue(0);
        strengthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strengthSliderStateChanged(evt);
            }
        });

        cbxPrivate.setText("Send Private");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectDefense, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCollectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(cbxAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fuelCount, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ammoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxPrivate)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnSend))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(strengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDefense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(fuelCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ammoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxPrivate)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(strengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        ammoCount.getAccessibleContext().setAccessibleName("Ammo Count\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCollectInfoActionPerformed

    private void cbxAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAreaClearActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_cbxAreaClearActionPerformed

    private void cbxAreaClearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAreaClearItemStateChanged
        // TODO add your handling code here:
         areaCleared=evt.getStateChange();
         observer.setArea(areaCleared);
            
          
    }//GEN-LAST:event_cbxAreaClearItemStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnSendMouseClicked

    private void btnSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMousePressed
        // TODO add your handling code here:
        
          //  mainMsg=txtSendMsg.getText();
          if(!cbxPrivate.isSelected()){
            observer.setMainMsg(txtSendMsg.getText()+"\n");
          }else{
              observer.setPrivateMsg((String)selectDefense.getSelectedItem(),txtSendMsg.getText());
          }
    
        
            
        
       
    }//GEN-LAST:event_btnSendMousePressed

    private void strengthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_strengthSliderStateChanged
        // TODO add your handling code here:

        
        observer.setStrength(strengthSlider.getValue());
    }//GEN-LAST:event_strengthSliderStateChanged

    private void selectDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDefenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDefenseActionPerformed

    private void selectDefensePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectDefensePropertyChange
        // TODO add your handling code here:
        
            selectDefense.getSelectedItem();
     
    }//GEN-LAST:event_selectDefensePropertyChange
   
    public boolean getArea(){
        return observer.getArea();
    }
    
    public void reciveMsg(String title,String msg){
            if(title.equals("Helicopter")){
                txtDisplayMsg.append("Helicopter"+" : "+msg);
                
            }else if(title.equals("Submarine")){
                txtDisplayMsg.append("Submarine"+" : "+msg);
                
               
            }else if(title.equals("Tank")){
                txtDisplayMsg.append("Tank"+" : "+msg);
                
            }
        
       
        txtDisplayMsg.append("\n");
        txtDisplayMsg.setLineWrap(true);
        
    }
//    public String getMsg(){
//        return msg;
//    }
    
    public String getMainMsg(){
        return txtSendMsg.getText();
    }
    //---------set private message-----
    
    //----------get private messege function--------
    public String getPrivateMsg(){
        return txtSendMsg.getText();
    }
//    public int getStrength(){
//        return strength;
//    }
     public StrengthEnum getStrength(){
        return observer.getStrength();
    }
    /**
     * @param args the command line arguments
     */
    
     //---------------------display details of defenses-------
     public void displayExtraDetais(String title,String lbl,String details){
         
         displayDetails.append(title+" : "+lbl+" = "+details+"\n");
     }
     
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController(observer).setVisible(true);
                //new MainController().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label ammoCount;
    private javax.swing.JButton btnCollectInfo;
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox cbxAreaClear;
    private javax.swing.JCheckBox cbxPrivate;
    private javax.swing.JTextArea displayDetails;
    private java.awt.Label fuelCount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JComboBox<String> selectDefense;
    private java.awt.Label soldierCount;
    private javax.swing.JSlider strengthSlider;
    private javax.swing.JTextArea txtDisplayMsg;
    private javax.swing.JTextArea txtSendMsg;
    // End of variables declaration//GEN-END:variables

    
}
